name: Deploy React Resume App with Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: Build and Deploy React App with Docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Build Environment
        run: |
          echo "Ensuring Docker is installed and running..."
          docker --version

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t react-resume-app:latest .

      - name: Run Docker Container
        run: |
          echo "Running Docker container..."
          docker stop react-resume-app || true
          docker rm react-resume-app || true
          docker run -d --name react-resume-app -p 80:80 react-resume-app:latest

      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          curl -I http://localhost || exit 1
